### PR TITLE
Add 1rem top margin to CategoryTree component

### PR DESCRIPTION
**Pull request by dustinjray**

### CODE REVIEW

**Comment by steven-lay** [comment]
Somehow the table of contents heading get messed up when I try browse the preview. Line height set to normal (from 150%) seems fixes it... Can anyone else confirm? 

Edit: actually a lot looks messed up like underlines appearing, not sure if it's just an issue with the preview.

image

**Comment by kevmodrome** [comment]
Hi thanks for the PR, but as mentioned above it looks a bit odd. It also needs to use the new css custom properties found here: https://github.com/svelte-society/sveltesociety.dev/blob/staging/src/lib/styles/root.css

**Comment by navneetsharmaui** [comment]
@kevmodrome Can I look into this issue if the PR is not touched by the Original contributor?

**Comment by kevmodrome** [comment]
> @kevmodrome Can I look into this issue if the PR is not touched by the Original contributor?

Definitely! Go for it.

**Comment by brittneypostma** [comment]
Closing due to inactivity, feel free to reopen if changes are made.

**Pull request closed without merging**
