### PR TITLE
add Link to "Svelte Component Test Recipes"

### PR DESCRIPTION
**Pull request by ivanhofer**

### CODE REVIEW

**Comment by benmccann** [comment]
I don't think this is how you're supposed to add a recipe. I don't see it showing up on the deploy preview at https://deploy-preview-313--sveltesociety-preview.netlify.app/recipes

I fixed the formatting, so if you rebase against the latest `staging` it should be fixed now

**Comment by ivanhofer** [comment]
Ah, right. But it shows up here: https://deploy-preview-313--sveltesociety-preview.netlify.app/recipes/testing-and-debugging
I'll fix it

**Comment by ivanhofer** [comment]
I have converted it to a new route that just contains the link

**Comment by kevmodrome** [comment]
Going to merge this.

PS. Seeing this PR makes me sad :(

**Pull request merged**
