### PR TITLE
Add actionview-svelte-handler to packages

### PR DESCRIPTION
**Pull request by reesericci**
## 🎯 Changes

Adds `actionview-svelte-handler` to packages

## ✅ Checklist

- [X] I have given my PR a descriptive title

### CODE REVIEW

**Comment by reesericci** [comment]
This doesn't use NPM, it's a rubygem, so I'm unsure on how to fix this error

**Comment by MacFJA** [comment]
> This doesn't use NPM, it's a rubygem, so I'm unsure on how to fix this error

It's a case we didn't anticipate.

I will open a new PR to allow other package sources

**Comment by reesericci** [comment]
The installation options should be:

**Gem**
```
gem install actionview-svelte-handler
```

**Bundler**
```
bundle add actionview-svelte-handler
```

These are like different ways of installing it, like NPM/PNPM/Yarn

**Comment by reesericci** [comment]
Added gem to packages.json, blocked by #652

**Comment by MacFJA** [comment]
> Added gem to packages.json, blocked by #652

The PR #652 have been merged.
Can you rebase your branch, so the validation can be done ?

**Comment by reesericci** [comment]
Rebased!

**Comment by MacFJA** [comment]
The package is available on the website: https://www.sveltesociety.dev/packages#actionview-svelte-handler

**Pull request merged**
