### PR TITLE
styling tweaks around the select component, created a new issue regar…

### PR DESCRIPTION
**Pull request by brittneypostma**
styling tweaks around the select component, created a new issue regarding the difficulties with this package

### CODE REVIEW

**Comment by benmccann** [comment]
I like that these are more like regular select components now. They're much harder to use though because the text is being cut off after eight characters and continued with ellipses. Is there a way to make the dropdown extend horizontally past the select component so that we can see more of the text. Also, it'd be nice to switch the package manager one as well so that they're all consistent.

**Comment by brittneypostma** [comment]
> 
> 
> I like that these are more like regular select components now. They're much harder to use though because the text is being cut off after eight characters and continued with ellipses. Is there a way to make the dropdown extend horizontally past the select component so that we can see more of the text. Also, it'd be nice to switch the package manager one as well so that they're all consistent.

This is exactly what I was referring to, I created an issue to not use that Svelte Select package. It is difficult to style consistently and it doesn't seem to have uncomplicated anything. This is just minor changes to at least make the buttons look better until we remove it.

**Comment by benmccann** [comment]
I wonder if we should just wait until then? I think this PR makes it look better in some ways, but makes it much harder to actually use due to that limitation

**Comment by kevmodrome** [comment]
Let's add an auto column grid here with a min width to achieve a two per row kind of thing here. That should also make it display nicely on mobile.

**Comment by brittneypostma** [comment]
> 
> 
> Let's add an auto column grid here with a min width to achieve a two per row kind of thing here. That should also make it display nicely on mobile.

So you want the inputs stacked on mobile and then 2 row with 2 inputs on each row on larger screens?

**Comment by brittneypostma** [comment]
I updated this to what I think you meant @kevmodrome and changed the searchbar to be more inline with the style of the inputs.

**Comment by benmccann** [comment]
this looks really nice. I might switch the package manager select as well, but other that this looks really good

**Comment by kevmodrome** [comment]
Sorry, been a bit busy lately (I know, recurring theme) - looks good.

**Comment by brittneypostma** [comment]
Sweet, no worries, I just started this week at my new job so I've been the same. I'm going to merge this, to avoid any conflicts with the other pr's. I can help take a look at those this weekend.

**Pull request merged**
