### PR TITLE
update link for CZ/SK society.

### PR DESCRIPTION
**Pull request by Mlocik97**

### CODE REVIEW

**Comment by benmccann** [comment]
both links appear to work to me. does it matter which we use?

**Comment by Mlocik97** [comment]
old one shows me "15 usages".

**Comment by benmccann** [comment]
What do you mean by that? I see the same thing with either link. Here's a screenshot

Screenshot from 2022-09-20 10-36-30

**Comment by Mlocik97** [comment]
I mean, if 15 people accept that invite, then it will be invalid? 16th one will be unable to connect via that link?

**Pull request merged**
