### PR TITLE
feat: Merge categories/tags and improve filtering

### PR DESCRIPTION
**Pull request by lachlancollins**
## 💭 Problem

This was prompted in part by discussion on #443. Tags are effectively unlimited and unregulated right now; however, categories are also quite limited since each entry can only have one. Filtering based on category/tags via the select fields is an okay experience - but it could be better!

## 🎯 Changes

Heavily inspired by [bestofjs.org](https://bestofjs.org/tags). Each item will be allowed multiple, pre-defined categories (or tags, the name doesn't matter). This would be a merge of current categories and useful tags to keep. By default, all entries are displayed. A collection of buttons let you choose which categories/tags you want displayed. When you select a category/tag, the list of available categories/tags narrows based on your current selection. This utilises a server load function, and the URL is shareable due to search params.

### Before

image

### After

image

image

image

## ✅ Checklist

- [x] I have given my PR a descriptive title
- [x] I have run `pnpm run lint` locally on my changes

### CODE REVIEW

**Comment by benmccann** [comment]
Honestly, I'm not a big fan of this as implemented. We commonly do things like link to https://sveltesociety.dev/packages#svelte-kit-adapters. There's no way to do that now as everything's just mixed together and that filter doesn't exist. It's also going to break tons of links that we have across svelte.dev and kit.svelte.dev. We could clean those up, but we'd need ways to keep the existing functionality for that to be possible

**Comment by kevmodrome** [comment]
This looks great!

**Comment by lachlancollins** [comment]
> Honestly, I'm not a big fan of this as implemented. We commonly do things like link to [sveltesociety.dev/packages#svelte-kit-adapters](https://sveltesociety.dev/packages#svelte-kit-adapters). There's no way to do that now as everything's just mixed together and that filter doesn't exist. It's also going to break tons of links that we have across svelte.dev and kit.svelte.dev. We could clean those up, but we'd need ways to keep the existing functionality for that to be possible

@benmccann oh wow fair enough, I had no idea it was referenced extensively in the svelte/kit docs. For that above link, with this change it would become https://sveltesociety.dev/packages?tag=svelte-kit-adapters. I guess the worst case scenario for old links is that users get taken to the top of the page rather than the category ID that was linked. I would argue this new solution is more robust than since it only loads the contents of the specific category/tag in the link. Either way, I'm not too fussed if this proposal isn't feasible since it was fun to implement!

**Comment by kevmodrome** [comment]
There is a feature in Cloudflare to do bulk redirects - maybe that's something we can explore?

**Comment by kevmodrome** [comment]
Given that we get the same functionality as before - would it be fine to merge this if we updated all the links on the Svelte site? @benmccann

**Comment by benmccann** [comment]
Let me give this another look to verify whether things like the `?tag=svelte-kit-adapters` filter will let us reproduce what we were depending on previously. I remember there being other issues we might need to address, but I can't check at the moment because the Netlify deploy is broken. Do we need to close this PR and open a new one to see the Vercel deploy preview or was the Netlify one taken down and the Vercel one not added yet?

**Comment by kevmodrome** [comment]
I think so.

**Comment by kevmodrome** [comment]
Testing Cloudflare Preview

**Comment by benmccann** [comment]
When I visit https://sveltesociety-dev-preview-git-fork-lachlan-97a95c-sveltesociety.vercel.app/packages it gives me a 500 error

**Comment by lachlancollins** [comment]
> When I visit [sveltesociety-dev-preview-git-fork-lachlan-97a95c-sveltesociety.vercel.app/packages](https://sveltesociety-dev-preview-git-fork-lachlan-97a95c-sveltesociety.vercel.app/packages) it gives me a 500 error

@benmccann this is fixed by #546 (the site wasn't using adapter-vercel)

**Comment by benmccann** [comment]
> For that above link, with this change it would become https://sveltesociety.dev/packages?tag=svelte-kit-adapters

Doesn't seem to work for me. This returns no results: https://sveltesociety-dev-preview-git-fork-lachlan-97a95c-sveltesociety.vercel.app/packages?tag=svelte-kit-adapters

**Comment by lachlancollins** [comment]
> > For that above link, with this change it would become https://sveltesociety.dev/packages?tag=svelte-kit-adapters
> 
> Doesn't seem to work for me. This returns no results: https://sveltesociety-dev-preview-git-fork-lachlan-97a95c-sveltesociety.vercel.app/packages?tag=svelte-kit-adapters

Yes sorry, I haven't actually merged categories and tags yet, I wanted to get some feedback before I put that effort in! Only existing tags (not categories) can be selected right now. For example: https://sveltesociety-dev-preview-git-fork-lachlan-97a95c-sveltesociety.vercel.app/packages?tag=notifications

**Comment by lachlancollins** [comment]
Hi @benmccann , would you be able to give this another look? Thanks!

**Pull request merged**
