### PR TITLE
add `sent-template` to templates.json

### PR DESCRIPTION
**Pull request by the-homeless-god**
@benmccann seems like it was non-migrated from the previous version of templates review like it was done by https://github.com/sveltejs/integrations/pull/56

### CODE REVIEW

**Comment by MacFJA** [comment]
@Zimtir, Can you rebase your branch with `staging` and run `npm run format`?

The file `src/routes/templates/templates.json` have formatting issues (incorrect white-space usage)

**Comment by the-homeless-god** [comment]
> @Zimtir, Can you rebase your branch with `staging` and run `npm run format`?
> 
> The file `src/routes/templates/templates.json` have formatting issues (incorrect white-space usage)

done, could you merge PR?

**Comment by the-homeless-god** [comment]
@MacFJA also seems like you have lint error at components.json that was unchanged by me

Should I fix it at my PR?

**Comment by MacFJA** [comment]
> @MacFJA also seems like you have lint error at components.json that was unchanged by me
> 
> Should I fix it at my PR?

Let me fix that.
Seem like I did a mistake

**Pull request merged**
