### PR TITLE
added preprocessor "svelte-remove-attributes"

### PR DESCRIPTION
**Pull request by jacobbogers**
preprocessor to remove attributes (like `data-testid` from production builds)

## 🎯 Change

added entry for a preprocessor

## ✅ Checklist

- [x] I have given my PR a descriptive title
- [x] I have run `pnpm run lint` locally on my changes

### CODE REVIEW

**Review by lachlancollins — CHANGES_REQUESTED** [review]
Hi @jacobbogers , you need to fix formatting, and the npm field should be the package name rather than a URL.

**Comment by jacobbogers** [comment]
> Hi @jacobbogers , you need to fix formatting, and the npm field should be the package name rather than a URL.

I have corrected, it is not an url but actual package name

**Review by lachlancollins — CHANGES_REQUESTED** [review]
Still failing linting, you need to fix the prettier issues.

**Comment by jacobbogers** [comment]
pnpm does not work for me, I am running prettier directly with --write, it did produce changes in package.json, so hope this works

**Comment by jacobbogers** [comment]
image

**Comment by jacobbogers** [comment]
`"lint": "prettier --check **/* --ignore-unknown && eslint . && node scripts/validateData.js",`

I am on windows, (11) remove the `'` around the  `**/*` and it will work for me,  does it work on linux/mac without `'` ?

**Review by lachlancollins — APPROVED** [review]

**Pull request merged**
