### PR TITLE
Update events section styling

### PR DESCRIPTION
**Pull request by diepoe**
I adjusted the stylings in the event section. I tried to use the provided css variables as much, thank you for bringing them up @brittneypostma!

### before
preview-before

### after
preview-after

### CODE REVIEW

**Comment by brittneypostma** [comment]
Looks like you might need to run `npm run lint`

**Comment by diepoe** [comment]
That isn't changing anything...  🤔
Bildschirmfoto 2021-10-02 um 20 27 15

**Comment by brittneypostma** [comment]
Hmm, looks like mine is failing too. Let me dig a little.

**Review by brittneypostma — APPROVED** [review]
Approving these as my pr should fix the linting issue and overall the styles look good. Thanks!

**Pull request merged**
