### PR TITLE
Add @sveltestack/svelte-query

### PR DESCRIPTION
**Pull request by frederikhors**

### CODE REVIEW

**Comment by benmccann** [comment]
It's already listed: https://github.com/svelte-society/sveltesociety-2021/blob/9b13ed6fd57b7154f2cef9165ed97bfc180e6415/src/routes/components/components.json#L2858

**Comment by frederikhors** [comment]
@benmccann I searched on the website for `query` and it's not present, see:

image

**Comment by benmccann** [comment]
I see it

Screenshot from 2021-07-29 20-22-29

Are you looking at the staging site? https://sveltesociety-2021-dqq.pages.dev/components

**Comment by frederikhors** [comment]
> Are you looking at the staging site?

Nope. Sorry. How many changes!

Can we publish it?

**Comment by benmccann** [comment]
Here's the todo list: https://github.com/svelte-society/sveltesociety-2021/issues/5

I have a PR out to get a good chunk of the way there: https://github.com/svelte-society/sveltesociety-2021/pull/32

**Comment by kevmodrome** [comment]
Closing this as it's already there.

**Pull request closed without merging**
