### PR TITLE
Add Awesome SvelteKit as discovery resource

### PR DESCRIPTION
**Pull request by janosh**
Add https://awesome-sveltekit.netlify.app to https://sveltesociety.dev/resources

Repo: https://github.com/janosh/awesome-sveltekit

### CODE REVIEW

**Comment by janosh** [comment]
Lint error unrelated to this change and also fixed in #304

**Comment by janosh** [comment]
@stephane-vanraes I hear you might be able to help with reviewing sveltesociety.dev PRs? Asking about this and #306.

**Comment by MacFJA** [comment]
@janosh Can you rebase your branch with `staging` ?
The lint issue is fixed on the current version of the `staging` branch.

**Comment by janosh** [comment]
@MacFJA Certainly.

**Comment by janosh** [comment]
@MacFJA Rebase done.

**Comment by janosh** [comment]
@MacFJA ping

**Pull request merged**
