### PR TITLE
add books section

### PR DESCRIPTION
**Pull request by tanhauhau**
add a section to list books about svelte

### CODE REVIEW

**Comment by pngwn** [comment]
Perhaps this should be called `Resources` and could be more general purpose?

**Comment by benmccann** [comment]
we should probably also move [the video faq](https://svelte.dev/faq#are-there-any-video-courses) here as well

I think this is too many menu items unfortunately especially since it ends up being off center. I don't have any great suggestions for how to handle it. We probably need an entirely new menu implementation. In the meantime, maybe we can remove the Cheat Sheet menu item and link to the Cheat Sheet from Recipes?

**Comment by benmccann** [comment]
@MacFJA @brittneypostma @kevmodrome do y'all have thoughts about how to handle this PR which adds another menu item? I listed one idea in my last comment, but wanted to get another opinion if possible before moving ahead with any decision

**Comment by brittneypostma** [comment]
Isn't @kevmodrome working on entirely new site design as well?

**Comment by brittneypostma** [comment]
In my opinion, if anything is going on this older site, resources should stay and have cheat sheet just go under resources.

**Pull request merged**
