### PR TITLE
Update societies.json - added Berlin meeting

### PR DESCRIPTION
**Pull request by nika-d**
## ✅ Checklist

- [x] I have given my PR a descriptive title
- [x] I have run `pnpm run lint` locally on my changes

### CODE REVIEW

**Comment by nika-d** [comment]
pnpm run lint failed first time: 

```
~/Desktop/temp/sveltesociety.dev$ pnpm run lint

> sveltesociety.dev@ lint /Users/nikadomanska/Desktop/temp/sveltesociety.dev
> prettier --check '**/*' --ignore-unknown && eslint . && node scripts/validateData.js

Checking formatting...
All matched files use Prettier code style!
file:///Users/nikadomanska/Desktop/temp/sveltesociety.dev/scripts/validateData.js:4
import packages from '../src/routes/packages/packages.json' assert { type: 'json' };
                                                            ^^^^^^

SyntaxError: Unexpected identifier 'assert'
    at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:164:18)
    at callTranslator (node:internal/modules/esm/loader:429:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:435:30)
    at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)

Node.js v22.3.0
 ELIFECYCLE  Command failed with exit code 1.
```

changing assert->with in validateData.js helps, cause of my node version. 

```
~/Desktop/temp/sveltesociety.dev$ pnpm run lint

> sveltesociety.dev@ lint /Users/nikadomanska/Desktop/temp/sveltesociety.dev
> prettier --check '**/*' --ignore-unknown && eslint . && node scripts/validateData.js

Checking formatting...
All matched files use Prettier code style!
(node:97016) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Validated packages.json
Validated templates.json
```

But it was not my intention to update scripts, thats why I did not push that change. 

If I should push it, please let me know! 

Kind regards,
Nika

**Comment by MacFJA** [comment]
The `url` seem like a one time event, and not a recurring event.

Do you intent to update the link when the event is past or when a new event is plan ?

**Comment by nika-d** [comment]
> The `url` seem like a one time event, and not a recurring event.
> 
> Do you intent to update the link when the event is past or when a new event is plan ?

Yes, definitely. We are building up our infrastructure, and probably luma structure will change. Currently, we have in mind an own luma-site for Svelte Berlin. This still is to be discussed with other Charité-IT communities, that are still in planning phase.

**Comment by MacFJA** [comment]
I will merge it, but it will be preferable if the `url` is fixed so you don't have to regularly create a new PR to have an up-to-date info, it will be one less things to remember to update.

**Comment by nika-d** [comment]
> I will merge it, but it will be preferable if the `url` is fixed so you don't have to regularly create a new PR to have an up-to-date info, it will be one less things to remember to update.

Yes, you are right! We will make one fixed url. Thank you for merging!

**Pull request merged**
