### PR TITLE
add `sthemer` to components

### PR DESCRIPTION
**Pull request by ivanhofer**

### CODE REVIEW

**Comment by benmccann** [comment]
this one has a merge conflict

**Comment by ivanhofer** [comment]
I have fixed the conflict

**Comment by benmccann** [comment]
looks good. a suggestion for the readme of the project would be to explain what benefits it has over just using css variables

**Comment by ivanhofer** [comment]
> looks good. a suggestion for the readme of the project would be to explain what benefits it has over just using css variables

It's kind of hidden in the [FAQ-section](https://github.com/ivanhofer/sthemer#faqs). I'll see how I can make this more prominent. Thanks for the feedback!

**Pull request merged**
