### PR TITLE
Release new version

### PR DESCRIPTION
**Pull request by kevmodrome**
@brittneypostma @benmccann would love a sanity check here before I go ahead and merge this into production

### CODE REVIEW

**Comment by brittneypostma** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/kevmodrome/reviewers)

**Comment by brittneypostma** [comment]
Left a comment on the preview showing the height on the home screen is off. Other than that, I believe this looks good. I don't blame you, that is a lot of changes :D

I can fix the height thing after if you want.

**Review by brittneypostma — APPROVED** [review]
Other than the height on the home screen being off, this looks good.

**Comment by benmccann** [comment]
lgtm. thanks

**Comment by brittneypostma** [comment]
Fixed the height issue, I'm going to go ahead and merge since everyone has had a chance to look it over.

**Pull request merged**
