### PR TITLE
Typeahead inputs

### PR DESCRIPTION
**Pull request by paolotiu**
Issue #79

Probably not the final version yet. Looking for feedback!

- [x] Make the dropdowns into text fields
 - [x] Add a label above
 - [x] Make sure there's an arrow that indicates there are options that show up once you click it
 - [ ] Use the same styling if possible
 - [x] Filter the options as you type in the input field

### CODE REVIEW

**Comment by kevmodrome** [comment]
I feel like the items could use some padding. Not sure exactly how I would want it to look, do you have any ideas @brittneypostma ?

**Comment by brittneypostma** [comment]
> I feel like the items could use some padding. Not sure exactly how I would want it to look, do you have any ideas @brittneypostma ?

Which items are you referencing?

**Comment by paolotiu** [comment]
> I feel like the items could use some padding. Not sure exactly how I would want it to look, do you have any ideas @brittneypostma ?

I'm assuming the items you're referring to are the dropdown items? If yes, then yeah I agree it could use some spacing.

**Comment by brittneypostma** [comment]
Components inputs and buttons screenshot

This alignment looks off to me as well. That button is massive and the dropdowns feel a bit scrunched. 

For the padding I would do this and maybe even add padding on the input itself as well:

```css
ul .popin {
padding: .5ex;
padding: .5rem;
display: grid;
gap: 0.25rem;
}
```

image

**Comment by brittneypostma** [comment]
I'm probably going to have to go through and update the styles in line with the new design system once it gets merged anyways. @kevmodrome if you are happy with the code changes, the styling I can deal with later.

**Comment by kevmodrome** [comment]
Sounds good! I'll merge this then.

**Pull request merged**
